# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hakkında.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(474, 214)
        Dialog.setMaximumSize(QtCore.QSize(474, 214))
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(10, 0, 441, 141))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("İmrakYazılım_İMkod.png"))
        self.label_20.setScaledContents(False)
        self.label_20.setWordWrap(False)
        self.label_20.setOpenExternalLinks(False)
        self.label_20.setObjectName("label_20")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 140, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Hakkında"))
        self.label.setText(_translate("Dialog", "Gmail: sanaldepo8@gmail.com"))
